#ifndef MIDIDEFINES_H_
#define MIDIDEFINES_H_

// Channel event types
#define MIDI_CHEVENT_INVALID 0x0
#define MIDI_CHEVENT_NOTEOFF 0x8
#define MIDI_CHEVENT_NOTEON 0x9
#define MIDI_CHEVENT_NOTEAFTERTOUCH 0xA
#define MIDI_CHEVENT_CONTROLLER 0xB
#define MIDI_CHEVENT_PROGRAMCHANGE 0xC
#define MIDI_CHEVENT_CHANNELAFTERTOUCH 0xD
#define MIDI_CHEVENT_PITCHBEND 0xE

#endif // MIDIDEFINES_H_
